"""Shared SQLAlchemy declarative base and mixins.

Why this exists: every model in the app (User, Movie, TVShow, Collection, ...)
needs the same three things — a consistent constraint-naming convention (so
Alembic autogenerate produces stable, greppable migration names instead of
opaque hashes), and consistent created_at/updated_at columns. Defining these
once here means new models in later phases just inherit `Base` and, where
relevant, `TimestampMixin` instead of re-declaring boilerplate.
"""

from datetime import datetime

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from sqlalchemy.sql import func

# Explicit naming convention so autogenerated Alembic migrations produce
# deterministic constraint names (e.g. "ix_movies_title" not "ix_1a2b3c").
# This matters at scale: unnamed constraints make future manual migrations
# (renaming a table, dropping a specific FK) painful to target reliably.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Base class for all ORM models in the application."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class TimestampMixin:
    """Adds created_at / updated_at columns, maintained by the database itself.

    Why server-side defaults (func.now()) rather than Python-side datetime.now():
    it keeps the timestamp authoritative and correct even under bulk inserts,
    multiple app instances with clock drift, or direct SQL access.
    """

    created_at: Mapped[datetime] = mapped_column(server_default=func.now(), nullable=False)
    updated_at: Mapped[datetime] = mapped_column(
        server_default=func.now(), onupdate=func.now(), nullable=False
    )
