"""initial schema

Revision ID: 62cf05922c4d
Revises:
Create Date: 2026-08-05 20:22:31.658052
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "62cf05922c4d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "genres",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_genres")),
        sa.UniqueConstraint("name", name=op.f("uq_genres_name")),
    )
    op.create_index(op.f("ix_genres_slug"), "genres", ["slug"], unique=True)
    op.create_table(
        "people",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=280), nullable=False),
        sa.Column("biography", sa.String(length=5000), nullable=True),
        sa.Column("profile_path", sa.String(length=500), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_people")),
    )
    op.create_index(op.f("ix_people_name"), "people", ["name"], unique=False)
    op.create_index(op.f("ix_people_slug"), "people", ["slug"], unique=True)
    op.create_table(
        "streaming_services",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("logo_path", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_streaming_services")),
        sa.UniqueConstraint("name", name=op.f("uq_streaming_services_name")),
    )
    op.create_index(op.f("ix_streaming_services_slug"), "streaming_services", ["slug"], unique=True)
    op.create_table(
        "titles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("media_type", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=280), nullable=False),
        sa.Column("overview", sa.Text(), nullable=True),
        sa.Column("tagline", sa.String(length=500), nullable=True),
        sa.Column("poster_path", sa.String(length=500), nullable=True),
        sa.Column("backdrop_path", sa.String(length=500), nullable=True),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("original_language", sa.String(length=10), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("popularity", sa.Float(), nullable=False),
        sa.Column("vote_average", sa.Float(), nullable=False),
        sa.Column("vote_count", sa.Integer(), nullable=False),
        sa.Column("is_oscar_winner", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_titles")),
    )
    op.create_index(op.f("ix_titles_media_type"), "titles", ["media_type"], unique=False)
    op.create_index(
        "ix_titles_media_type_popularity", "titles", ["media_type", "popularity"], unique=False
    )
    op.create_index(op.f("ix_titles_popularity"), "titles", ["popularity"], unique=False)
    op.create_index(op.f("ix_titles_release_date"), "titles", ["release_date"], unique=False)
    op.create_index(op.f("ix_titles_slug"), "titles", ["slug"], unique=True)
    op.create_index(op.f("ix_titles_title"), "titles", ["title"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=True),
        sa.Column("avatar_path", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "collections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_collections_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collections")),
    )
    op.create_index(op.f("ix_collections_user_id"), "collections", ["user_id"], unique=False)
    op.create_table(
        "credits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title_id", sa.Integer(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=False),
        sa.Column("department", sa.String(length=20), nullable=False),
        sa.Column("character_name", sa.String(length=255), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["people.id"],
            name=op.f("fk_credits_person_id_people"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["title_id"], ["titles.id"], name=op.f("fk_credits_title_id_titles"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credits")),
    )
    op.create_index(op.f("ix_credits_person_id"), "credits", ["person_id"], unique=False)
    op.create_index(op.f("ix_credits_title_id"), "credits", ["title_id"], unique=False)
    op.create_table(
        "favorites",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["title_id"],
            ["titles.id"],
            name=op.f("fk_favorites_title_id_titles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_favorites_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "title_id", name=op.f("pk_favorites")),
    )
    op.create_table(
        "movies",
        sa.Column("title_id", sa.Integer(), nullable=False),
        sa.Column("runtime_minutes", sa.Integer(), nullable=True),
        sa.Column("budget", sa.Integer(), nullable=True),
        sa.Column("revenue", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["title_id"], ["titles.id"], name=op.f("fk_movies_title_id_titles"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("title_id", name=op.f("pk_movies")),
    )
    op.create_table(
        "ratings",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("review_text", sa.String(length=5000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "score >= 1 AND score <= 10", name=op.f("ck_ratings_score_between_1_and_10")
        ),
        sa.ForeignKeyConstraint(
            ["title_id"], ["titles.id"], name=op.f("fk_ratings_title_id_titles"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_ratings_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "title_id", name=op.f("pk_ratings")),
    )
    op.create_table(
        "roulette_spins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("filters", sa.JSON(), nullable=False),
        sa.Column("result_title_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["result_title_id"],
            ["titles.id"],
            name=op.f("fk_roulette_spins_result_title_id_titles"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_roulette_spins_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roulette_spins")),
    )
    op.create_index(op.f("ix_roulette_spins_user_id"), "roulette_spins", ["user_id"], unique=False)
    op.create_table(
        "title_availability",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title_id", sa.Integer(), nullable=False),
        sa.Column("streaming_service_id", sa.Integer(), nullable=False),
        sa.Column("region", sa.String(length=2), nullable=False),
        sa.Column("watch_url", sa.String(length=1000), nullable=True),
        sa.ForeignKeyConstraint(
            ["streaming_service_id"],
            ["streaming_services.id"],
            name=op.f("fk_title_availability_streaming_service_id_streaming_services"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["title_id"],
            ["titles.id"],
            name=op.f("fk_title_availability_title_id_titles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_title_availability")),
        sa.UniqueConstraint(
            "title_id", "streaming_service_id", "region", name="uq_title_availability"
        ),
    )
    op.create_index(
        op.f("ix_title_availability_streaming_service_id"),
        "title_availability",
        ["streaming_service_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_title_availability_title_id"), "title_availability", ["title_id"], unique=False
    )
    op.create_table(
        "title_genres",
        sa.Column("title_id", sa.Integer(), nullable=False),
        sa.Column("genre_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["genre_id"],
            ["genres.id"],
            name=op.f("fk_title_genres_genre_id_genres"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["title_id"],
            ["titles.id"],
            name=op.f("fk_title_genres_title_id_titles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("title_id", "genre_id", name=op.f("pk_title_genres")),
    )
    op.create_table(
        "tv_shows",
        sa.Column("title_id", sa.Integer(), nullable=False),
        sa.Column("number_of_seasons", sa.Integer(), nullable=True),
        sa.Column("number_of_episodes", sa.Integer(), nullable=True),
        sa.Column("episode_runtime_minutes", sa.Integer(), nullable=True),
        sa.Column("last_air_date", sa.Date(), nullable=True),
        sa.Column("in_production", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["title_id"],
            ["titles.id"],
            name=op.f("fk_tv_shows_title_id_titles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("title_id", name=op.f("pk_tv_shows")),
    )
    op.create_table(
        "viewing_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title_id", sa.Integer(), nullable=False),
        sa.Column(
            "viewed_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["title_id"],
            ["titles.id"],
            name=op.f("fk_viewing_history_title_id_titles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_viewing_history_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_viewing_history")),
    )
    op.create_index(
        op.f("ix_viewing_history_title_id"), "viewing_history", ["title_id"], unique=False
    )
    op.create_index(
        op.f("ix_viewing_history_user_id"), "viewing_history", ["user_id"], unique=False
    )
    op.create_index(
        "ix_viewing_history_user_viewed_at",
        "viewing_history",
        ["user_id", "viewed_at"],
        unique=False,
    )
    op.create_table(
        "watch_later_items",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["title_id"],
            ["titles.id"],
            name=op.f("fk_watch_later_items_title_id_titles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_watch_later_items_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "title_id", name=op.f("pk_watch_later_items")),
    )
    op.create_table(
        "collection_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("collection_id", sa.Integer(), nullable=False),
        sa.Column("title_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "added_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.id"],
            name=op.f("fk_collection_items_collection_id_collections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["title_id"],
            ["titles.id"],
            name=op.f("fk_collection_items_title_id_titles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collection_items")),
        sa.UniqueConstraint("collection_id", "title_id", name="uq_collection_item"),
    )
    op.create_index(
        op.f("ix_collection_items_collection_id"),
        "collection_items",
        ["collection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_collection_items_title_id"), "collection_items", ["title_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_collection_items_title_id"), table_name="collection_items")
    op.drop_index(op.f("ix_collection_items_collection_id"), table_name="collection_items")
    op.drop_table("collection_items")
    op.drop_table("watch_later_items")
    op.drop_index("ix_viewing_history_user_viewed_at", table_name="viewing_history")
    op.drop_index(op.f("ix_viewing_history_user_id"), table_name="viewing_history")
    op.drop_index(op.f("ix_viewing_history_title_id"), table_name="viewing_history")
    op.drop_table("viewing_history")
    op.drop_table("tv_shows")
    op.drop_table("title_genres")
    op.drop_index(op.f("ix_title_availability_title_id"), table_name="title_availability")
    op.drop_index(
        op.f("ix_title_availability_streaming_service_id"), table_name="title_availability"
    )
    op.drop_table("title_availability")
    op.drop_index(op.f("ix_roulette_spins_user_id"), table_name="roulette_spins")
    op.drop_table("roulette_spins")
    op.drop_table("ratings")
    op.drop_table("movies")
    op.drop_table("favorites")
    op.drop_index(op.f("ix_credits_title_id"), table_name="credits")
    op.drop_index(op.f("ix_credits_person_id"), table_name="credits")
    op.drop_table("credits")
    op.drop_index(op.f("ix_collections_user_id"), table_name="collections")
    op.drop_table("collections")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_titles_title"), table_name="titles")
    op.drop_index(op.f("ix_titles_slug"), table_name="titles")
    op.drop_index(op.f("ix_titles_release_date"), table_name="titles")
    op.drop_index(op.f("ix_titles_popularity"), table_name="titles")
    op.drop_index("ix_titles_media_type_popularity", table_name="titles")
    op.drop_index(op.f("ix_titles_media_type"), table_name="titles")
    op.drop_table("titles")
    op.drop_index(op.f("ix_streaming_services_slug"), table_name="streaming_services")
    op.drop_table("streaming_services")
    op.drop_index(op.f("ix_people_slug"), table_name="people")
    op.drop_index(op.f("ix_people_name"), table_name="people")
    op.drop_table("people")
    op.drop_index(op.f("ix_genres_slug"), table_name="genres")
    op.drop_table("genres")
    # ### end Alembic commands ###
